### ISSUE TITLE
Incompatible with Pyramid 1.10 due to removal of set_request_property

### ISSUE THREAD

**Issue by Deimos** [sontek/pyramid_webassets#65]
Pyramid 1.10 has removed the `pyramid.config.Configurator.set_request_property` method (which has been deprecated since 1.5): https://docs.pylonsproject.org/projects/pyramid/en/latest/whatsnew-1.10.html#backward-incompatibilities

pyramid_webassets uses this, so it currently crashes when used with Pyramid 1.10: https://github.com/sontek/pyramid_webassets/blob/4109bbaf37eaf6a010b6f061a07b6175657644e7/pyramid_webassets/__init__.py#L396-L398

**Comment by tilgovi** [comment]
Would you make a PR replacing it with `add_request_method`, please? We can then make sure all the tests pass and release a 0.10 version.

**Comment by Deimos** [comment]
Sure, I can do the PR if someone can do a release for it. Thanks.

**Comment by tilgovi** [comment]
Closed by #66 and released as v0.10. Thanks, @Deimos!
